name: first-ci
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up test
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          c devops && make install
      - name: Lint
        run: |
          cd devops && make lint
      - name: Test
        run: |
          cd devops && make test
